*   Nome: Ian Rodrigues dos Reis Paixão
*   Matrícula: 166394
*   Código de Pessoa: 1026447
-------------------------------------------
*   Nome: Rithie Natan Carvalhaes Prado
*   Matrícula: 166395     
*   Código de Pessoa: 998694
-------------------------------------------

# YuGiOh Cards Prediction
-------------------------------------------
Referências:
*   https://www.kaggle.com/datasets/ioexception/yugioh-cards
*   https://ygoprodeck.com/


> Yu-Gi-Oh! é um jogo de cartas colecionáveis desenvolvido pela Konami. O jogo foi lançado no Japão em 1999 e rapidamente se tornou popular em todo o mundo. Yu-Gi-Oh! é baseado no mangá e anime de mesmo nome, criado por Kazuki Takahashi.

> O jogo é jogado entre dois jogadores, cada um com um baralho de 40 a 60 cartas. O objetivo do jogo é reduzir os pontos de vida do oponente a zero. Os jogadores podem fazer isso jogando monstros no campo, que podem atacar os monstros do oponente ou seus pontos de vida diretamente. Os jogadores também podem jogar feitiços e armadilhas para afetar o campo de batalha e o jogo em si

> Existem vários tipos diferentes de cartas em Yu-Gi-Oh!, cada uma com seus próprios pontos de ataque e defesa. Os monstros podem ser de diferentes atributos, como fogo, água, terra e vento. Eles também podem ser de diferentes tipos, como besta, guerreiro, mago etc. Os feitiços podem ser usados para convocar monstros, atacar monstros ou destruir cartas. As armadilhas podem ser usadas para prevenir ataques, destruir cartas ou desviar ataques

> Aqui estão os componentes de uma carta de Yu-Gi-Oh:


* Nome: O nome da carta.
* Tipo: O tipo da carta, como Monstro, Magia ou Armadilha.
* Atributo: O atributo da carta, como Fogo, Água, Terra, Vento ou Luz.
* Nível: O nível da carta, que determina quantas cartas detributo você pode oferecer como tributo para invocá-la.
* Ataque: O ataque da carta, que determina quantas vidas do seu oponente você pode tirar quando ataca.
* Defesa: A defesa da carta, que determina quantas vidas você pode proteger quando é atacado.
* Efeito: O efeito da carta, que descreve o que ela pode fazer.
* Imagem: A imagem da carta, que geralmente é do monstro ou feitiço que representa.



> As cartas de Yu-Gi-Oh! são divididas em 3 tipos principais:

*   Cartas do tipo Monstro: https://shorturl.at/dkwH2

*   Cartas do tipo Feitiço: https://shorturl.at/fgmtz

*   Cartas do tipo Armadilha: https://shorturl.at/kwDP4








> As cartas do tipo Monstro por sua vez apresentam as seguinte subdivisões:


*   Monstros do tipo Normal: https://shorturl.at/dkwH2

*   Monstros do tipo Efeito: https://shorturl.at/bcdlO

*   Monstros do tipo Ritual: https://shorturl.at/KOVZ9

*   Monstros do tipo Fusão: https://shorturl.at/hpO09

*   Monstros do tipo Synchro: https://shorturl.at/zHMNY

*   Monstros do tipo XYZ: https://shorturl.at/asCD6

*   Monstros do tipo Pendulum: https://shorturl.at/emBSU

*   Monstros do tipo Link: https://shorturl.at/gIMY6


> Os ultimos 5 ou seja ( Fusão, Synchro, XYZ, Pendulum e Link) são cosiderados como monstros de Extra Deck.

> Extra é um deck a parte do deck principal que pode ter até 15 cartas dos tipo Monstro descritos acima como monstro de Extra Deck.

-------------------------------------------------------------------------------
> Neste trabalho utilizaremos o banco de dados disponibilzado via Kaggle que contem todas as cartas do Jogo. A partir dessas cartas trabalharemos em primeiro momento somente com as carts do tipo Monstro e mais especificamente com cartas do tipo Monstro de Extra Deck.

> Treinaremos um modelo de treinamento super visionados para aprender a prever o Tipo de Monstro do Extra Deck (Fusão, Synchro, XYZ, Pendulum e Link).

> Iremos validar o modelo usando um outro dataset de cartas de Monstro que podem conter dos os tipo de Monstros.
------------------------------------------------------------------------------
> Iremos usar metodos de Natural language Processing para determinar qual o efeito de carta mais presente nas 200 cartas mais utilizadas na plataforma Master Duel

> Yu-Gi-Oh! Master Duel é um jogo de cartas colecionáveis baseado na franquia Yu-Gi-Oh!. O jogo foi lançado em 2022 para PlayStation 4, PlayStation 5, Xbox One, Xbox Series X/S, Nintendo Switch, Microsoft Windows e dispositivos móveis.

## Imports

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import missingno as msno
%matplotlib inline
import random
import nltk
import spacy
import pydotplus
import re
from sklearn.preprocessing import MinMaxScaler, KBinsDiscretizer, OrdinalEncoder, OneHotEncoder , PowerTransformer , RobustScaler , StandardScaler, LabelEncoder
from sklearn.impute import SimpleImputer
from sklearn.impute import KNNImputer
from imblearn.under_sampling import CondensedNearestNeighbour, TomekLinks, EditedNearestNeighbours, OneSidedSelection, NeighbourhoodCleaningRule
from imblearn.over_sampling import RandomOverSampler, SMOTE, BorderlineSMOTE, ADASYN
from sklearn.tree import DecisionTreeClassifier
from sklearn.feature_extraction import DictVectorizer
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.model_selection import train_test_split, RandomizedSearchCV, GridSearchCV
from time import time
from IPython.display import Image
from sklearn.naive_bayes import GaussianNB, MultinomialNB, ComplementNB, BernoulliNB, CategoricalNB
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from spacy.lang.en.stop_words import STOP_WORDS
from string import punctuation
from nltk.util import ngrams
from nltk.corpus import stopwords
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.corpus import wordnet
from heapq import nlargest

## Carregando datasets


In [ ]:
allcards = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/cards.csv')
allcards_cardsets = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/cards_cardsets.csv')
allcards_variants = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/cards_variants.csv')
allcardsets = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/cardsets.csv')
topused = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/master_top_used_cards.csv')
random = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/random_monster_300_cards_validation.csv')
randomeff = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/random_monster_300_cards_validation_without_effect_monster.csv')
randomextranormal = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/random_monster_300_cards_validation_without_extra_normal.csv')
randomnormal = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/random_monster_300_cards_validation_without_only_normal.csv')

In [ ]:
allcards.head()

id                           name        type  \
0  34541863       "A" Cell Breeding Device  Spell Card   
1  64163367             "A" Cell Incubator  Spell Card   
2  91231901  "A" Cell Recombination Device  Spell Card   
3  73262676         "A" Cell Scatter Burst  Spell Card   
4  98319530     "Infernoble Arms - Almace"  Spell Card   

                                                desc  atk  def  level  \
0  During each of your Standby Phases, put 1 A-Co...  NaN  NaN    NaN   
1  Each time an A-Counter(s) is removed from play...  NaN  NaN    NaN   
2  Target 1 face-up monster on the field; send 1 ...  NaN  NaN    NaN   
3  Select 1 face-up "Alien" monster you control. ...  NaN  NaN    NaN   
4  While this card is equipped to a monster: You ...  NaN  NaN    NaN   

         race attribute  scale  ...   views  viewsweek upvotes downvotes  \
0  Continuous       NaN    NaN  ...  285555          0     118       110   
1  Continuous       NaN    NaN  ...  200924          0      25        20   
2  Quick-Play       NaN    NaN  ...  208890          0      19        15   
3  Quick-Play       NaN    NaN  ...  157723          0      12         4   
4       Equip       NaN    NaN  ...    6845          0       0         0   

                                    formats treated_as    tcg_date  \
0  Duel Links|Common Charity|Edison|TCG|OCG        NaN  2007-05-16   
1  Duel Links|Common Charity|Edison|TCG|OCG        NaN  2007-11-14   
2         Duel Links|Common Charity|TCG|OCG        NaN  2016-11-03   
3  Duel Links|Common Charity|Edison|TCG|OCG        NaN  2007-02-28   
4                                       OCG        NaN         NaN   

     ocg_date konami_id  has_effect  
0  2007-02-15    7128.0           1  
1  2007-07-21    7315.0           1  
2  2016-07-09   12653.0           1  
3  2006-11-16    6994.0           1  
4  2023-04-22   18843.0           1  

[5 rows x 29 columns]

## Machine Learning:

### Seleção do dataset de cartas e trativas

In [ ]:
allcards.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12648 entries, 0 to 12647
Data columns (total 29 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   id               12648 non-null  int64  
 1   name             12648 non-null  object 
 2   type             12648 non-null  object 
 3   desc             12648 non-null  object 
 4   atk              8231 non-null   float64
 5   def              7850 non-null   float64
 6   level            7850 non-null   float64
 7   race             12647 non-null  object 
 8   attribute        8231 non-null   object 
 9   scale            333 non-null    float64
 10  archetype        7286 non-null   object 
 11  linkval          381 non-null    float64
 12  linkmarkers      381 non-null    object 
 13  image_url        12648 non-null  object 
 14  image_url_small  12648 non-null  object 
 15  ban_tcg          192 non-null    object 
 16  ban_ocg          190 non-null    object 
 17  ban_goat    

In [ ]:
# Aqui estamos eliminando colunas que trazem informações secundárias sobre as cartas e que não fazem sentido para nossa proposta.
Cards =  allcards.drop(['image_url','image_url_small','ban_tcg','ban_ocg','ban_goat','staple','views','viewsweek','upvotes','downvotes','formats','treated_as','tcg_date','ocg_date','konami_id','has_effect'], axis=1)

### Seleção de cartas do tipo Monstro

In [ ]:
#Filtrando todas as cartas que não do tipo Monstro
Cards = Cards[Cards['type'] != 'Skill Card']
Cards = Cards[Cards['type'] != 'Spell Card']
Monsters = Cards[Cards['type'] != 'Trap Card']

In [ ]:
Monsters.head()

id                       name                 type  \
9   86988864             3-Hump Lacooda       Effect Monster   
10  11714098   30,000-Year White Turtle       Normal Monster   
11  83994646  4-Starred Ladybug of Doom  Flip Effect Monster   
13  23771716             7 Colored Fish       Normal Monster   
15  14261867           8-Claws Scorpion       Effect Monster   

                                                 desc     atk     def  level  \
9   If there are 3 face-up "3-Hump Lacooda" cards ...   500.0  1500.0    3.0   
10  A huge turtle that has existed for more than 3...  1250.0  2100.0    5.0   
11  FLIP: Destroy all Level 4 monsters your oppone...   800.0  1200.0    3.0   
13  A rare rainbow fish that has never been caught...  1800.0   800.0    4.0   
15  Once per turn, you can flip this card into fac...   300.0   200.0    2.0   

      race attribute  scale archetype  linkval linkmarkers  
9    Beast     EARTH    NaN       NaN      NaN         NaN  
10    Aqua     WATER    NaN       NaN      NaN         NaN  
11  Insect      WIND    NaN       NaN      NaN         NaN  
13    Fish     WATER    NaN       NaN      NaN         NaN  
15  Insect      DARK    NaN       NaN      NaN         NaN

In [ ]:
Monsters['type'].value_counts()

Effect Monster                     4520
Normal Monster                      657
XYZ Monster                         489
Fusion Monster                      437
Tuner Monster                       437
Synchro Monster                     402
Link Monster                        381
Pendulum Effect Monster             254
Flip Effect Monster                 178
Ritual Effect Monster               111
Token                               107
Gemini Monster                       45
Pendulum Normal Monster              42
Union Effect Monster                 36
Spirit Monster                       33
Synchro Tuner Monster                23
Toon Monster                         17
Ritual Monster                       15
Pendulum Effect Fusion Monster       11
Normal Tuner Monster                 10
XYZ Pendulum Effect Monster           9
Pendulum Tuner Effect Monster         8
Synchro Pendulum Effect Monster       7
Pendulum Effect Ritual Monster        1
Pendulum Flip Effect Monster          1


### Seleção das cartas de Monstros do Extra Deck

In [ ]:
# Uma vez filtrados os Monstros seguimos filtrando buscando somente Monstros de Extra Deck!
Monstersfiltered = Monsters[Monsters['type'] != 'Effect Monster']
Monstersfiltered = Monstersfiltered[Monstersfiltered['type'] != 'Normal Monster']
Monstersfiltered = Monstersfiltered[Monstersfiltered['type'] != 'Tuner Monster']
Monstersfiltered = Monstersfiltered[Monstersfiltered['type'] != 'Flip Effect Monster']
Monstersfiltered = Monstersfiltered[Monstersfiltered['type'] != 'Token']
Monstersfiltered = Monstersfiltered[Monstersfiltered['type'] != 'Ritual Effect Monster']
Monstersfiltered = Monstersfiltered[Monstersfiltered['type'] != 'Gemini Monster']
Monstersfiltered = Monstersfiltered[Monstersfiltered['type'] != 'Union Effect Monster']
Monstersfiltered = Monstersfiltered[Monstersfiltered['type'] != 'Spirit Monster']
Monstersfiltered = Monstersfiltered[Monstersfiltered['type'] != 'Toon Monster']
Monstersfiltered = Monstersfiltered[Monstersfiltered['type'] != 'Ritual Monster']
ExtraMonsters = Monstersfiltered[Monstersfiltered['type'] != 'Normal Tuner Monster']

In [ ]:
ExtraMonsters.head()

id                          name                     type  \
31  65172015   A-to-Z-Dragon Buster Cannon           Fusion Monster   
42   1561110             ABC-Dragon Buster           Fusion Monster   
56  15308295    Abyss Actor - Comic Relief  Pendulum Effect Monster   
57  44179224  Abyss Actor - Curtain Raiser  Pendulum Effect Monster   
58  52240819       Abyss Actor - Evil Heel  Pendulum Effect Monster   

                                                 desc     atk     def  level  \
31  "ABC-Dragon Buster" + "XYZ-Dragon Cannon"\nMus...  4000.0  4000.0   10.0   
42  "A-Assault Core" + "B-Buster Drake" + "C-Crush...  3000.0  2800.0    8.0   
56  [ Pendulum Effect ] You can target 1 "Abyss Ac...  1000.0  2000.0    3.0   
57  [ Pendulum Effect ]\r\nIf you control no monst...  1100.0  1000.0    4.0   
58  [ Pendulum Effect ]\r\nOnce per turn: You can ...  3000.0  2000.0    8.0   

       race attribute  scale    archetype  linkval linkmarkers  
31  Machine     LIGHT    NaN          ABC      NaN         NaN  
42  Machine     LIGHT    NaN          ABC      NaN         NaN  
56    Fiend      DARK    8.0  Abyss Actor      NaN         NaN  
57    Fiend      DARK    7.0  Abyss Actor      NaN         NaN  
58    Fiend      DARK    1.0  Abyss Actor      NaN         NaN

In [ ]:
ExtraMonsters.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2065 entries, 31 to 12642
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   id           2065 non-null   int64  
 1   name         2065 non-null   object 
 2   type         2065 non-null   object 
 3   desc         2065 non-null   object 
 4   atk          2065 non-null   float64
 5   def          1684 non-null   float64
 6   level        1684 non-null   float64
 7   race         2065 non-null   object 
 8   attribute    2065 non-null   object 
 9   scale        333 non-null    float64
 10  archetype    1488 non-null   object 
 11  linkval      381 non-null    float64
 12  linkmarkers  381 non-null    object 
dtypes: float64(5), int64(1), object(7)
memory usage: 225.9+ KB


In [ ]:
ExtraMonsters.fillna('', inplace=True)

<ipython-input-2384-5273e2e98e0c>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ExtraMonsters.fillna('', inplace=True)


###: Separação para Treino e Teste

In [ ]:
# Separamos em uma variavel a coluna que carrega a informaão do tipo da Carta e utlizaremos essa variavel para a construção do y
Extras = ExtraMonsters.iloc[:,ExtraMonsters.columns == 'type']
ExtrasArray = Extras.values.flatten()
ExtrasArray

array(['Fusion Monster', 'Fusion Monster', 'Pendulum Effect Monster', ...,
       'XYZ Monster', 'Synchro Monster', 'XYZ Monster'], dtype=object)

In [ ]:
# Construção do X usando as colunas de nome, arquetipo e descrição, estas contem informações suficientes para uma previsão de um tipo
enc = OrdinalEncoder()
X = ExtraMonsters[['name', 'archetype', 'desc']]
X = enc.fit_transform(X)
X.shape

(2065, 3)

In [ ]:
# Propriamente criando o y
le = LabelEncoder()
y = le.fit_transform(ExtrasArray)
y.shape

(2065,)

In [ ]:
le.classes_

array(['Fusion Monster', 'Link Monster', 'Pendulum Effect Fusion Monster',
       'Pendulum Effect Monster', 'Pendulum Effect Ritual Monster',
       'Pendulum Flip Effect Monster', 'Pendulum Normal Monster',
       'Pendulum Tuner Effect Monster', 'Synchro Monster',
       'Synchro Pendulum Effect Monster', 'Synchro Tuner Monster',
       'XYZ Monster', 'XYZ Pendulum Effect Monster'], dtype=object)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0) # SEED

### Decision Tree

In [ ]:
Extras_tree = DecisionTreeClassifier(random_state=0,  criterion='entropy',  max_depth=30,min_samples_leaf=2)# Utilizamos o resultado encontrado do Grid Search e comentamos o bloco para ganho de memoria e tempo!
Extras_tree = Extras_tree.fit(X_train, y_train)

In [ ]:
#n_iter_search = 100 # numero de iteracoes/execucoes aleatórias do algoritmo
# specify parameters and distributions to sample from
#tree_params = {"max_depth": np.arange(0, 31),
#               "criterion": ["entropy", "log_loss"],
#               "min_samples_split": np.arange(0, 5),
#               "min_samples_leaf": np.arange(0, 5),
#               }
#tree_params
#grid_search = GridSearchCV(Extras_tree,
                          # cv=5,
                          # param_grid=tree_params)

#start = time()
#grid_search.fit(X_train, y_train)

#print("GridSerachCV took %.2f seconds for %d candidates"
#      " parameter settings \n\n" % ((time() - start), n_iter_search))
#Extras_tree = grid_search.best_estimator_

In [ ]:
Extras_tree.predict(X_train)

array([ 3, 11,  1, ..., 11, 11, 11])

In [ ]:
y_train

array([ 3, 11,  1, ..., 11, 11, 11])

In [ ]:
print("Acurácia (base de treinamento):", Extras_tree.score(X_train, y_train))

Acurácia (base de treinamento): 0.9487889273356401


In [ ]:
y_pred = Extras_tree.predict(X_test)

In [ ]:
print("Acurácia de previsão:", accuracy_score(y_test, y_pred))

Acurácia de previsão: 0.817741935483871


In [ ]:
cnf_matrix = confusion_matrix(y_test, y_pred)
print(cnf_matrix)

[[107  13   0   0   0   0   0  10   0   2   0]
 [ 20  89   0   0   0   0   0   1   0   4   0]
 [  0   0   2   1   0   0   0   0   0   0   0]
 [  0   0   5  67   0   1   0   0   0   0   2]
 [  0   0   1   0   0   0   0   0   0   0   0]
 [  1   0   0   7   0   6   0   0   0   0   0]
 [  0   0   0   2   0   1   0   0   0   0   0]
 [ 15   1   0   0   0   0   0 101   4   0   0]
 [  0   0   0   0   0   0   0  10   1   0   0]
 [  3   4   0   0   0   0   0   0   0 134   0]
 [  0   0   2   3   0   0   0   0   0   0   0]]


### Naive Bayes

In [ ]:
# Aqui selecionamos alguns dos Modelos De Naives Bayes e os subtemos aos mesmo X e Y ao qual a arvore de decisão foi submetida
gaussianNB = GaussianNB()
multiNB = MultinomialNB()
compNB = ComplementNB()
berNB = BernoulliNB()
catNB = CategoricalNB()

nb_model = gaussianNB.fit(X_train, y_train)
print("Acurácia do modelo no treino: GaussianNB", round(nb_model.score(X_train, y_train),2)*100)
#
nb_model = multiNB.fit(X_train, y_train)
print("Acurácia do modelo no treino: MultinomialNB", round(nb_model.score(X_train, y_train),2)*100)
#
nb_model = compNB.fit(X_train, y_train)
print("Acurácia do modelo no treino: ComplementNB", round(nb_model.score(X_train, y_train),2)*100)
#
nb_model = berNB.fit(X_train, y_train)
print("Acurácia do modelo no treino: BernoulliNB", round(nb_model.score(X_train, y_train),2)*100)

Acurácia do modelo no treino: GaussianNB 65.0
Acurácia do modelo no treino: MultinomialNB 21.0
Acurácia do modelo no treino: ComplementNB 27.0
Acurácia do modelo no treino: BernoulliNB 25.0


In [ ]:
ansgau = gaussianNB.score(X_test, y_test)
print("Acurácia do modelo no teste: GaussianNB", round(ansgau,2)*100)
#
ansmult = multiNB.score(X_test, y_test)
print("Acurácia do modelo no teste: MultinomialNB", round(ansmult,2)*100)
#
anscomp = compNB.score(X_test, y_test)
print("Acurácia do modelo no teste: ComplementNB", round(anscomp,2)*100)
#
ansber = berNB.score(X_test, y_test)
print("Acurácia do modelo no teste: BernoulliNB", round(ansber,2)*100)

Acurácia do modelo no teste: GaussianNB 66.0
Acurácia do modelo no teste: MultinomialNB 25.0
Acurácia do modelo no teste: ComplementNB 28.000000000000004
Acurácia do modelo no teste: BernoulliNB 26.0


In [ ]:
y_pred = gaussianNB.predict(X_test)

In [ ]:
(y_test != y_pred).sum()

208

In [ ]:
print("Número de erros de classificação MultinomialNB  {0} de {1}"
      .format((y_test != y_pred).sum(), len(y_pred)))

Número de erros de classificação MultinomialNB  208 de 620


### Considerações Pós Treino e Teste:

> Comparados os desempenhos dos Modelos treinados acima, o Grupo julga a árvore de decisão como o modelo mais satisfátorio para o desenvolvimento da proposta.



### Validação

Nesta parte final, o objetivo foi verificar a predição do algoritmo utilizado para diversos datasets.
Os datasets utilizados, as cartas residentes, na sua maioria não estão presentes no modelo de treinamento e teste. Portanto, a expectativa é observar o comportamento do modelo a partir de seus erros.

Os datasets de validação foram divididos da seguinte forma:
* Total de 300 cartas.
* Apenas contém tipo monstros em geral.
* O dataset de ***normal monster*** contém apenas monstros do tipo Normal e Fusão.
* O restante dos datasets foram mixados entre diversos tipos de monstros do tipo efeito e suas variantes.

Resultados preliminares:
* Foi observado uma generalização do modelo para todos resultados.
* Os resultados apresentaram acertos, porém apresenta as respostas com apenas um tipo.

In [ ]:
random.fillna('', inplace=True)

In [ ]:
random[random['name'] == 'Dark Rebellion Xyz Dragon']

Unnamed: 0        id                       name         type  \
124        2531  16195942  Dark Rebellion Xyz Dragon  XYZ Monster   

                                                  desc     atk     def level  \
124  2 Level 4 monsters\r\nYou can detach 2 materia...  2500.0  2000.0   4.0   

       race attribute scale archetype linkval linkmarkers  
124  Dragon      DARK

In [ ]:
randomeff.fillna('', inplace=True)

In [ ]:
randomeff[randomeff['name'] == 'Crystal Clear Wing Synchro Dragon']

Unnamed: 0        id                               name             type  \
51        2077  59765225  Crystal Clear Wing Synchro Dragon  Synchro Monster   

                                                 desc     atk     def level  \
51  1 Tuner Synchro Monster + 1 non-Tuner "Clear W...  3000.0  2500.0  10.0   

      race attribute scale   archetype linkval linkmarkers  
51  Dragon      WIND        Clear Wing

In [ ]:
randomnormal.fillna('', inplace=True)

In [ ]:
randomnormal[randomnormal['name'] == 'Ryu-Ran']

Unnamed: 0       id     name            type  \
44        9359  2964201  Ryu-Ran  Normal Monster   

                                                 desc     atk     def  level  \
44  A vicious little dragon sheltered in an egg th...  2200.0  2600.0    7.0   

      race attribute scale archetype linkval linkmarkers  
44  Dragon      FIRE

In [ ]:
randomextranormal.fillna('', inplace=True)

In [ ]:
randomextranormal[randomextranormal['name'] == 'Cyber Dragon Infinity']

Unnamed: 0        id                   name         type  \
66        2168  10443957  Cyber Dragon Infinity  XYZ Monster   

                                                 desc     atk     def level  \
66  3 Level 6 LIGHT Machine monsters\r\nOnce per t...  2100.0  1600.0   6.0   

       race attribute scale     archetype linkval linkmarkers  
66  Machine     LIGHT        Cyber Dragon

In [ ]:
yrandom = le.fit_transform(random[['type']].values.flatten())
#
yrandomeff = le.fit_transform(randomeff[['type']].values.flatten())
#
yrandomormal = le.fit_transform(randomnormal[['type']].values.flatten())
#
yrandomextranormal = le.fit_transform(randomextranormal[['type']].values.flatten())

In [ ]:
yrandom = yrandom.reshape(-1, 3)
#
yrandomeff = yrandomeff.reshape(-1, 3)
#
yrandomormal = yrandomormal.reshape(-1, 3)
#
yrandomextranormal = yrandomextranormal.reshape(-1, 3)

In [ ]:
treepred = Extras_tree.predict(yrandom)
treepred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
treepredeff= Extras_tree.predict(yrandomeff)
treepredeff

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
treeprednormal= Extras_tree.predict(yrandomormal)
treeprednormal

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
treepredextranormal= Extras_tree.predict(yrandomextranormal)
treepredextranormal

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
reversedtree = le.inverse_transform(treepred)

In [ ]:
reversedtreeeff = le.inverse_transform(treepredeff)

In [ ]:
reversedtreenormal = le.inverse_transform(treeprednormal)

In [ ]:
reversedtreeextranormal = le.inverse_transform(treepredextranormal)

In [ ]:
gausspred = gaussianNB.predict(yrandom)
gausspred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
gausspredeff = gaussianNB.predict(yrandomeff)
gausspredeff

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
gaussprednormal = gaussianNB.predict(yrandomormal)
gaussprednormal

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
gausspredextranormal = gaussianNB.predict(yrandomextranormal)
gausspredextranormal

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
reservedgauss = le.inverse_transform(gausspred)

In [ ]:
reservedgausseff = le.inverse_transform(gausspredeff)

In [ ]:
reservedgaussnormal = le.inverse_transform(gaussprednormal)

In [ ]:
reservedgaussextranormal = le.inverse_transform(gausspredextranormal)

## Natural Language Processing

> Nesta seção do Notebook iremos trabalha acima do dataset das 200 cartas mais usadas no Aplicativo Oficial de Yu-Gi-Oh!: Master Duel.

> Usando esse dataset iremos extrair palavras chaves encontradas nas da descrição dos efeitos das cartas.

> Uma vez extraidas as palavras chaves iremos analisar qual a palavra chave que tem a maior representatividade nessas 200 cartas.








In [ ]:
# Declarações necessárias para o desvenvolvimento da parte de Natural Language Processing
stopwords = list(STOP_WORDS)
nlp = spacy.load("en_core_web_sm")

In [ ]:
# Aqui vamos criar uma copia do dataset, eliminando colunas que trazem informações secundárias sobre as cartas e que não fazem sentido para nossa proposta.
Top =  topused.drop(['image_url','image_url_small','ban_tcg','ban_ocg','ban_goat','staple','views','viewsweek','upvotes','downvotes','formats','treated_as','tcg_date','ocg_date','konami_id','has_effect'], axis=1)

In [ ]:
#Exemplo de uma carta que está no dataset
Top[Top['name'] == 'Ash Blossom & Joyous Spring']

Unnamed: 0        id                         name           type  \
199         199  14558127  Ash Blossom & Joyous Spring  Tuner Monster   

                                                  desc  atk     def  level  \
199  When a card or effect is activated that includ...  0.0  1800.0    3.0   

       race attribute  scale archetype  linkval linkmarkers  
199  Zombie      FIRE    NaN       NaN      NaN         NaN

In [ ]:
#Juntamos todas as descrições das 200 cartas nessa variável uma vez que é a Descrição que carrega as palavras chaves que iremos extrair para desenvolver o trabalho
all = Top['desc'].astype("string")

In [ ]:
#Extração das palavras chaves das descrições. Escolhemos as palavras que mais trazem consigo um significado maior de interação entre os Duelistas
all = all.str.extract(r'(Negate|negate|Banish|banish|Destroy|destroy|Send|send|Discard|discard|Attacks|attacks|Draw|draw|Add|add|Equip|equip|cannot target|Inflict|inflict)')

In [ ]:
# Tarnsformação em string e retirado de \n
result = all.to_string(index = False)
result = re.sub(r"\s+", " ", result)

### Word tokenization:

In [ ]:
doc = nlp(result)

In [ ]:
tokens = [token.text for token in doc]
punctuation = punctuation + punctuation

In [ ]:
word_frequencies = {}
for word in doc:
  if word.text.lower() not in stopwords:
    if word.text.lower() not in punctuation:
      if word.text not in word_frequencies.keys():
        word_frequencies[word.text] = 1
      else:
        word_frequencies[word.text] += 1
word_frequencies

{' ': 1,
 '0': 1,
 'destroy': 25,
 'negate': 21,
 'discard': 12,
 'banish': 26,
 'Add': 5,
 'attacks': 3,
 'send': 21,
 'draw': 6,
 'Banish': 7,
 'add': 19,
 'equip': 5,
 'NA': 15,
 'target': 7,
 'inflict': 2,
 'Equip': 1,
 'Negate': 4,
 'Destroy': 6,
 'Send': 7,
 'Discard': 3,
 'Draw': 5}

### Word Frequency:

In [ ]:
max_frequency = max(word_frequencies.values())
max_frequency
ans = ''
for word in word_frequencies.keys():
  word_frequencies[word] = word_frequencies[word]/max_frequency
  ans = (word_frequencies)
  sentence_tokens = [sent for sent in doc.sents]
ans

{' ': 0.038461538461538464,
 '0': 0.038461538461538464,
 'destroy': 0.9615384615384616,
 'negate': 0.8076923076923077,
 'discard': 0.46153846153846156,
 'banish': 1.0,
 'Add': 0.19230769230769232,
 'attacks': 0.11538461538461539,
 'send': 0.8076923076923077,
 'draw': 0.23076923076923078,
 'Banish': 0.2692307692307692,
 'add': 0.7307692307692307,
 'equip': 0.19230769230769232,
 'NA': 0.5769230769230769,
 'target': 0.2692307692307692,
 'inflict': 0.07692307692307693,
 'Equip': 0.038461538461538464,
 'Negate': 0.15384615384615385,
 'Destroy': 0.23076923076923078,
 'Send': 0.2692307692307692,
 'Discard': 0.11538461538461539,
 'Draw': 0.19230769230769232}

### Word frequency table:

In [ ]:
sentence_scores = {}
for sent in sentence_tokens:
  for word in sent:
    if word.text.lower() in word_frequencies.keys():
      if sent not in sentence_scores.keys():
        sentence_scores[sent] = word_frequencies[word.text.lower()]
      else:
        sentence_scores[sent] += word_frequencies[word.text.lower()]
sentence_scores

{ 0 destroy negate discard banish banish Add attacks destroy destroy destroy banish banish negate discard destroy send send draw Banish destroy negate add equip draw add draw banish destroy add destroy <: 22.653846153846146,
 NA> add Banish negate destroy cannot target <NA>: 3.769230769230769,
 Add negate destroy negate inflict negate Equip equip banish inflict <: 5.653846153846154,
 NA> negate equip Banish banish banish Negate send draw negate Destroy banish add banish Add add destroy add destroy negate <NA> send negate add add Send Send send cannot target add <: 21.76923076923076,
 NA> banish Send draw destroy send negate cannot target negate add <NA> draw banish destroy send add add send add destroy equip destroy <: 14.538461538461537,
 NA> banish send Negate banish send send add negate attacks Destroy negate add Negate Discard send Draw Draw banish send Draw add banish send <NA> discard discard Discard send Send Banish destroy send add destroy destroy discard discard negate banish 

### Summarization:

In [ ]:
from heapq import nlargest
select_length = int(len(sentence_tokens)*0.3)
select_length
summary = nlargest(select_length, sentence_scores, key = sentence_scores.get)
summary
final_summary = [word.text for word in summary]
summary = "".join(final_summary)
summary

'NA> banish send Negate banish send send add negate attacks Destroy negate add Negate Discard send Draw Draw banish send Draw add banish send <NA> discard discard Discard send Send Banish destroy send add destroy destroy discard discard negate banish discard < 0 destroy negate discard banish banish Add attacks destroy destroy destroy banish banish negate discard destroy send send draw Banish destroy negate add equip draw add draw banish destroy add destroy <NA> negate equip Banish banish banish Negate send draw negate Destroy banish add banish Add add destroy add destroy negate <NA> send negate add add Send Send send cannot target add <'

### Conclusão


> Os dados mostram que os efeitos mais comuns das cartas de Yu-Gi-Oh são destruir, negar, banir e enviar. Esses efeitos são poderosos e podem ter um impacto significativo no jogo. Por exemplo, destruir um monstro pode impedir que seu oponente o ataque, negar um efeito pode impedir que seu oponente ative um card, banir um card pode retirar recursos deu seu oponente e enviar um card para o cemitério pode permitir que você ative seu efeito.
--------------------------------------------------------------------------------
> A palavra “banir” aparece com mais frequência na tabela de frequência de palavras, com uma frequência de 22,65%. Isso sugere que o banimento é um efeito muito poderoso em Yugioh. Quando uma carta é banida, ela é totalmente removida do jogo e não pode ser devolvida ao campo. Esta pode ser uma maneira muito eficaz de se livrar de cartões problemáticos.
--------------------------------------------------------------------------------
> Com base nos resultados do Summary das palavras-chave dos efeitos da carta Yugioh, os efeitos mais comuns são banir, enviar e negar. Isso sugere que esses são alguns dos efeitos mais poderosos e versáteis do jogo.
--------------------------------------------------------------------------------
> A palavra "banir" aparece duas vezes mais do que qualquer outra palavra, o que sugere que é um efeito muito poderoso. O banimento remove totalmente uma carta do jogo, o que pode ser uma maneira muito eficaz de se livrar de cartas problemáticas.

--------------------------------------------------------------------------------
> Aprofundando no efeito de Banir, Banir uma carta é removê-la do jogo. Ela fica banida até que uma carta ou efeito específico a retire de banimento. Banir uma carta pode ser uma maneira eficaz de se livrar de um monstro forte ou de impedir que um efeito seja ativado.
--------------------------------------------------------------------------------
> Exemplo de carta que tem em seu efeito a palavra chave Banir: https://shorturl.at/gnyGM

